#!/usr/bin/env bash
#Ping an IP address 5 times

MSG="Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
if [ $# -eq 0 ];
then
    echo "$MSG"
else
    for ip_add in "$@"; do
        ping -c 5 "$ip_add"
    done
fi
